# Generated by Django 2.2.1 on 2019-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
